name: 'Jira Upload Deployment Info'
description: 'Github Action to upload deployment info associated with a Jira issue key to Jira Software REST API'
inputs:
  cloud-instance-base-url:
    description: 'Jira cloud url'
    required: true
  client-id:
    description: 'jira oauth client id'
    required: true
  client-secret:
    description: 'jira oauth client secret'
    required: true
  deployment-sequence-number:
    description: ''
    required: false
  update-sequence-number:
    description: ''
    required: false
  issue-keys:
    description: 'comma delimited list of jira keys'
    required: true
  display-name:
    description: ''
    required: true
  url:
    description: ''
    required: false
  description:
    description: ''
    required: true
  last-updated:
    description: ''
    required: true
  label:
    description: ''
    required: true
  state:
    description: ''
    required: true
  pipeline-id:
    description: ''
    required: false
  pipeline-display-name:
    description: ''
    required: false
  pipeline-url:
    description: ''
    required: false
  environment-id:
    description: ''
    required: true
  environment-display-name:
    description: ''
    required: true
  environment-type:
    description: ''
    required: true

outputs:
  response:
    description: 'Response from upload deployment info endpoint of Jira Software REST API'
runs:
  using: 'node16'
  main: 'index.js'
